version: "3.8"
services:
  api:
    image: venttys
    build: .
    environment: 
      - PORT=80
      - ENV=development
    volumes: 
      - ./public:/home/app/public
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 80:80